idf_component_register(
    SRCS
        "main.cpp"
        "modules/SerialManager.cpp"
        "modules/WiFiManager.cpp"
        "modules/EthernetManager.cpp"
        "modules/Keyboard.cpp"
        "modules/DisplayTM1640.cpp"
        "modules/ADC_AD7191.cpp"
        "modules/PowerManager.cpp"
        "modules/CashDrawer.cpp"
        "modules/StatusLED.cpp"
        "modules/WebServer.cpp"
        "utils/Logger.cpp"
        "modules/OtaManager.cpp"
    INCLUDE_DIRS
        "."
        "modules"
        "utils"
    REQUIRES
        "esp_tinyusb"
        "esp_http_client"
        "esp_https_ota"
        "esp_http_server"
        "esp_wifi"
        "esp_eth"        
        "nvs_flash"
        "esp_event"
        "esp_netif"
        "driver"
        "esp_timer"
        "mbedtls"
)